# Describes the format for available cover services

open_cover:
  description: Open all or specified cover
  target:
    entity:
      domain: cover

close_cover:
  description: Close all or specified cover
  target:
    entity:
      domain: cover

toggle:
  description: Toggles a cover open/closed
  target:
    entity:
      domain: cover

set_cover_position:
  description: Move to specific position all or specified cover
  target:
    entity:
      domain: cover
  fields:
    position:
      name: Position
      description: Position of the cover
      required: true
      example: 30
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

stop_cover:
  description: Stop all or specified cover
  target:
    entity:
      domain: cover

open_cover_tilt:
  description: Open all or specified cover tilt
  target:
    entity:
      domain: cover

close_cover_tilt:
  description: Close all or specified cover tilt
  target:
    entity:
      domain: cover

toggle_cover_tilt:
  description: Toggles a cover tilt open/closed
  target:
    entity:
      domain: cover

set_cover_tilt_position:
  description: Move to specific position all or specified cover tilt
  target:
    entity:
      domain: cover
  fields:
    tilt_position:
      name: Tilt position
      description: Tilt position of the cover.
      required: true
      example: 30
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

stop_cover_tilt:
  description: Stop all or specified cover
  target:
    entity:
      domain: cover
