# Describes the format for available alarm control panel services

alarm_disarm:
  description: Send the alarm the command for disarm
  target:
    entity:
      domain: alarm_control_panel
  fields:
    code:
      name: Code
      description: An optional code to disarm the alarm control panel with.
      example: "1234"
      selector:
        text:

alarm_arm_custom_bypass:
  description: Send arm custom bypass command
  target:
    entity:
      domain: alarm_control_panel
  fields:
    code:
      name: Code
      description:
        An optional code to arm custom bypass the alarm control panel with.
      example: "1234"
      selector:
        text:

alarm_arm_home:
  description: Send the alarm the command for arm home
  target:
    entity:
      domain: alarm_control_panel
  fields:
    code:
      name: Code
      description: An optional code to arm home the alarm control panel with.
      example: "1234"
      selector:
        text:

alarm_arm_away:
  description: Send the alarm the command for arm away
  target:
    entity:
      domain: alarm_control_panel
  fields:
    code:
      name: Code
      description: An optional code to arm away the alarm control panel with.
      example: "1234"
      selector:
        text:

alarm_arm_night:
  description: Send the alarm the command for arm night
  target:
    entity:
      domain: alarm_control_panel
  fields:
    code:
      name: Code
      description: An optional code to arm night the alarm control panel with.
      example: "1234"
      selector:
        text:

alarm_trigger:
  description: Send the alarm the command for trigger
  target:
    entity:
      domain: alarm_control_panel
  fields:
    code:
      name: Code
      description: An optional code to trigger the alarm control panel with.
      example: "1234"
      selector:
        text:
