# Describes the format for available automation services
turn_on:
  description: Enable an automation
  target:
    entity:
      domain: automation

turn_off:
  description: Disable an automation
  target:
    entity:
      domain: automation
  fields:
    stop_actions:
      name: Stop actions
      description: Stop currently running actions.
      default: true
      example: true
      selector:
        boolean:

toggle:
  description: Toggle an automation
  target:
    entity:
      domain: automation

trigger:
  description: Trigger the action of an automation
  target:
    entity:
      domain: automation
  fields:
    skip_condition:
      name: Skip conditions
      description: Whether or not the condition will be skipped.
      default: true
      example: true
      selector:
        boolean:

reload:
  description: Reload the automation configuration
